# Generated by Django 4.0.4 on 2022-05-05 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nylas_email_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Folder',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Label',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('snippet', models.CharField(max_length=500)),
                ('starred', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=500)),
                ('unread', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
        migrations.CreateModel(
            name='MessageParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reply_to', 'Reply To'), ('to', 'To'), ('from', 'From'), ('cc', 'Cc'), ('bcc', 'Bcc')], max_length=100)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nylas_email_app.message')),
            ],
            options={
                'verbose_name': 'Message Participant',
            },
        ),
        migrations.CreateModel(
            name='NylasUserAccount',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('organization_unit', models.CharField(choices=[('label', 'Label'), ('folder', 'Folder')], max_length=10)),
                ('sync_state', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('invalid', 'Invalid')], max_length=10)),
                ('linked_at', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nylas User Account',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Participant',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_message_timestamp', django_unixdatetimefield.fields.UnixDateTimeField(null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('last_message_received_timestamp', django_unixdatetimefield.fields.UnixDateTimeField(null=True)),
                ('last_message_sent_timestamp', django_unixdatetimefield.fields.UnixDateTimeField(null=True)),
                ('last_message_timestamp', django_unixdatetimefield.fields.UnixDateTimeField(null=True)),
                ('starred', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=500)),
                ('unread', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=0)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nylas_email_app.nylasuseraccount')),
                ('folders', models.ManyToManyField(related_name='threads', to='nylas_email_app.folder')),
                ('labels', models.ManyToManyField(related_name='threads', to='nylas_email_app.label')),
            ],
            options={
                'verbose_name': 'Thread',
            },
        ),
        migrations.DeleteModel(
            name='UserNylasDetail',
        ),
        migrations.AddField(
            model_name='messageparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nylas_email_app.participant'),
        ),
        migrations.AddField(
            model_name='message',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nylas_email_app.nylasuseraccount'),
        ),
        migrations.AddField(
            model_name='message',
            name='folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nylas_email_app.folder'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to_message_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nylas_email_app.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nylas_email_app.thread'),
        ),
        migrations.AddField(
            model_name='label',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nylas_email_app.nylasuseraccount'),
        ),
        migrations.AddField(
            model_name='folder',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nylas_email_app.nylasuseraccount'),
        ),
    ]
