# Generated by Django 4.0.4 on 2022-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nylas_email_app', '0003_alter_message_reply_to_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nylasuseraccount',
            name='linked_at',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='first_message_timestamp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='last_message_received_timestamp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='last_message_sent_timestamp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='last_message_timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
