# Generated by Django 4.0.4 on 2022-05-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nylas_email_app', '0004_alter_message_date_alter_nylasuseraccount_linked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nylasuseraccount',
            name='linked_at',
        ),
    ]
