# Generated by Django 4.0.4 on 2022-05-05 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nylas_email_app', '0005_remove_nylasuseraccount_linked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nylasuseraccount',
            name='linked_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 12, 55, 16, 329899, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
